# Copyright 2023 Dimitri Koshkin. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: checks

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install tools via asdf
        uses: asdf-vm/actions/install@v2.2.0
        with:
          asdf_branch: v0.11.2

      - name: Run unit tests
        run: make test

      - name: Annotate tests
        if: always()
        uses: guyarb/golang-test-annotations@v0.7.0
        with:
          test-results: test.json

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Gather tool versions
        uses: endorama/asdf-parse-tool-versions@v1
        id: versions

      - name: github-actions-lint
        uses: reviewdog/action-actionlint@v1
        with:
          fail_on_error: true
          reporter: github-pr-review

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          fail_on_error: true
          reporter: github-pr-review
          go_version: v${{ fromJson(steps.versions.outputs.tools).golang }}
          golangci_lint_version: v${{ fromJson(steps.versions.outputs.tools).golangci-lint }}

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Gather tool versions
        uses: endorama/asdf-parse-tool-versions@v1
        id: versions

      - uses: actions/setup-go@v4
        with:
          go-version: ${{ fromJson(steps.versions.outputs.tools).golang }}
          check-latest: false
          cache: true

      - uses: mfinelli/setup-shfmt@v3
        with:
          shfmt-version: ${{ fromJson(steps.versions.outputs.tools).shfmt }}

      - uses: pre-commit/action@v3.0.0
        with:
          extra_args: --all-files --show-diff-on-failure
        env:
          SKIP: no-commit-to-branch,golangci-lint

  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install tools via asdf
        uses: asdf-vm/actions/install@v2.2.0
        with:
          asdf_branch: v0.11.2

      - name: Build
        run: make build-snapshot

      - name: Run binary
        run: |
          ./dist/status-writer-action_linux_amd64_v1/status-writer-action --version

  run-with-influxdb:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install tools via asdf
        uses: asdf-vm/actions/install@v2.2.0
        with:
          asdf_branch: v0.11.2

      - name: Build
        run: make build-snapshot

      - name: Run status-writer-action with InfluxDB
        uses: ./.github/composite-actions/status-writer
        # always run this step, even if previous steps fail
        if: always()
        with:
          # select the backend to use
          backend: "influxdb"
          # set InfluxDB details
          influxdb_token: "${{ secrets.INFLUXDB_TOKEN }}"
          influxdb_url: "${{ secrets.INFLUXDB_URL }}"
          influxdb_org: "${{ secrets.INFLUXDB_ORG }}"
          influxdb_bucket: "${{ secrets.INFLUXDB_BUCKET }}"

  run-with-googlesheets:
    runs-on: ubuntu-latest
    env:
      GOOGLE_APPLICATION_CREDENTIALS: client_secret.json
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install tools via asdf
        uses: asdf-vm/actions/install@v2.2.0
        with:
          asdf_branch: v0.11.2

      - name: Build
        run: make build-snapshot

      - name: Write Google Cloud credentials to file
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "${{ env.GOOGLE_APPLICATION_CREDENTIALS }}"
          json: "${{ secrets.GOOGLE_CREDENTIALS }}"

      - name: Run status-writer-action with Google Sheets
        uses: ./.github/composite-actions/status-writer
        # always run this step, even if previous steps fail
        if: always()
        with:
          # select the backend to use
          backend: "googlesheets"
          # set Google Sheets details
          googlesheets_spreadsheet_id: "${{ secrets.GOOGLESHEETS_SPREADSHEET_ID }}"
