# Copyright 2023 Dimitri Koshkin. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: release-checks

on:
  workflow_dispatch:
  workflow_call:

jobs:
  test-with-influxdb:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run status-writer-action action locally
        uses: ./.github/composite-actions/status-writer-released
        if: always()
        with:
          # select the backend to use
          backend: "influxdb"
          # set InfluxDB details
          influxdb_token: "${{ secrets.INFLUXDB_TOKEN }}"
          influxdb_url: "${{ secrets.INFLUXDB_URL }}"
          influxdb_org: "${{ secrets.INFLUXDB_ORG }}"
          influxdb_bucket: "${{ secrets.INFLUXDB_BUCKET }}"

  test-with-googlesheets:
    runs-on: ubuntu-latest
    env:
      GOOGLE_APPLICATION_CREDENTIALS: client_secret.json
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Write Google Cloud credentials to file
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "${{ env.GOOGLE_APPLICATION_CREDENTIALS }}"
          json: "${{ secrets.GOOGLE_CREDENTIALS }}"

      - name: Run status-writer-action action locally
        uses: ./.github/composite-actions/status-writer-released
        if: always()
        with:
          # select the backend to use
          backend: "googlesheets"
          # set Google Sheets details
          googlesheets_spreadsheet_id: "${{ secrets.GOOGLESHEETS_SPREADSHEET_ID }}"
