# Copyright 2023 Dimitri Koshkin. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: release-checks

on:
  workflow_dispatch:
  workflow_call:

jobs:
  test-with-influxdb:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run status-writer-action action locally
        uses: ./.github/composite-actions/status-writer-released
        if: always()
        with:
          # select the backend to use
          backend: "influxdb"
          # set InfluxDB details
          influxdb_token: "${{ secrets.INFLUXDB_TOKEN }}"
          influxdb_url: "${{ secrets.INFLUXDB_URL }}"
          influxdb_org: "${{ secrets.INFLUXDB_ORG }}"
          influxdb_bucket: "${{ secrets.INFLUXDB_BUCKET }}"
          # set the status and additional metadata tags
          repository: "${{ github.repository }}"
          actor: "${{ github.actor }}"
          status: "${{ job.status }}"
          tags: "workflow=${{ github.workflow }},job=${{ github.job }},ref=${{ github.ref_name }},run_number=${{ github.run_number }},run_id=${{ github.run_id }}"
