# Copyright 2023 Dimitri Koshkin. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: template-sync

on:
  schedule:
    - cron:  "0 * * * *"
  workflow_dispatch:

jobs:
  template-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Sync repo template
        uses: AndreasAugustin/actions-template-sync@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_repo_path: dkoshkin/golang-repository-template
          pr_title: "chore: sync template changes"
          pr_commit_msg: "chore(template): sync template changes :up:"
